"""add_docker_tests

Revision ID: 06e8c7f8139a
Revises: a88aec136b59
Create Date: 2024-04-15 18:23:09.224330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from src.submission.models import ResultType

# revision identifiers, used by Alembic.
revision: str = '06e8c7f8139a'
down_revision: Union[str, None] = 'aa8ad1b4f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('type', ENUM(ResultType, name='resulttype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('test_files_uuid', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'remarks')
    op.drop_column('project', 'test_files_uuid')
    op.drop_table('testresult')
    enum = ENUM(ResultType, name='resulttype')
    enum.drop(op.get_bind())
    # ### end Alembic commands ###
