"""add groups

Revision ID: 0b71bf916b62
Revises: 5a1ed3366cce
Create Date: 2024-03-13 16:58:06.437972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b71bf916b62'
down_revision: Union[str, None] = '5a1ed3366cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('team_name', sa.String(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('student_group',
                    sa.Column('uid', sa.String(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
                    sa.ForeignKeyConstraint(['uid'], ['website_user.uid'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_group')
    op.drop_table('team')
    # ### end Alembic commands ###
