"""change studentgroup

Revision ID: 1d969eb58cf1
Revises: 0b71bf916b62
Create Date: 2024-03-13 21:17:13.264653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d969eb58cf1'
down_revision: Union[str, None] = '0b71bf916b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_group', sa.Column('project_id', sa.NullType(), nullable=True))
    op.add_column('student_group', sa.Column('score', sa.NullType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_group', 'score')
    op.drop_column('student_group', 'project_id')
    # ### end Alembic commands ###
