"""add uuid files and requirements for project

Revision ID: 5011e8183104
Revises: 76859289ea2d
Create Date: 2024-03-27 21:50:17.418154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5011e8183104'
down_revision: Union[str, None] = '76859289ea2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('mandatory', sa.Boolean(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('submission', sa.Column('files_uuid', sa.String(), nullable=False))
    op.drop_constraint('teacher_subject_uid_fkey',
                       'teacher_subject', type_='foreignkey')
    op.drop_constraint('teacher_subject_subject_id_fkey',
                       'teacher_subject', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_subject', 'subject', [
                          'subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subject', 'website_user',
                          ['uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.create_foreign_key('teacher_subject_subject_id_fkey',
                          'teacher_subject', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key('teacher_subject_uid_fkey',
                          'teacher_subject', 'website_user', ['uid'], ['uid'])
    op.drop_column('submission', 'files_uuid')
    op.drop_table('requirement')
    # ### end Alembic commands ###
