"""Add is_teacher column

Revision ID: 5917675f28ab
Revises: 76859289ea2d
Create Date: 2024-03-20 14:44:13.652699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5917675f28ab'
down_revision: Union[str, None] = '76859289ea2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('website_user', sa.Column(
        'is_teacher', sa.Boolean(), nullable=False, server_default='f'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_user', 'is_teacher')
    # ### end Alembic commands ###
