"""add_docker_tests

Revision ID: 6ceb31bcf295
Revises: a88aec136b59
Create Date: 2024-04-14 17:28:29.958915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ceb31bcf295'
down_revision: Union[str, None] = 'a88aec136b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('test_files_uuid', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'remarks')
    op.drop_column('project', 'test_files_uuid')
    op.drop_table('testresult')
    # ### end Alembic commands ###
