"""add submission

Revision ID: 76859289ea2d
Revises: c93f08ebb01e
Create Date: 2024-03-14 20:42:17.075566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76859289ea2d'
down_revision: Union[str, None] = 'c93f08ebb01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.Enum('InProgress', 'Accepted',
                                                'Denied', name='status'), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['team.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
