"""teacher is now called instructor

Revision ID: 85fa9f187230
Revises: 5917675f28ab
Create Date: 2024-03-22 23:54:26.482767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fa9f187230'
down_revision: Union[str, None] = '5917675f28ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_subject',
                    sa.Column('uid', sa.String(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
                    sa.ForeignKeyConstraint(['uid'], ['website_user.uid'], )
                    )
    op.drop_table('teacher_subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subject',
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('subject_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'],
                                            name='teacher_subject_subject_id_fkey'),
                    sa.ForeignKeyConstraint(['uid'], ['website_user.uid'],
                                            name='teacher_subject_uid_fkey')
                    )
    op.drop_table('instructor_subject')
    # ### end Alembic commands ###
