"""is_teacher_boolean_and_instructor

Revision ID: a88aec136b59
Revises: 5011e8183104
Create Date: 2024-04-03 21:47:10.758518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88aec136b59'
down_revision: Union[str, None] = '5011e8183104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_subject',
                    sa.Column('uid', sa.String(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['subject_id'], ['subject.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['uid'], ['website_user.uid'], ondelete='CASCADE')
                    )
    op.drop_table('teacher_subject')
    op.add_column('website_user', sa.Column('is_teacher', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_user', 'is_teacher')
    op.create_table('teacher_subject',
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('subject_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'],
                                            name='teacher_subject_subject_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['uid'], ['website_user.uid'],
                                            name='teacher_subject_website_user_fkey', ondelete='CASCADE')
                    )
    op.drop_table('instructor_subject')
    # ### end Alembic commands ###
