"""add_capacity

Revision ID: aa8ad1b4f8dc
Revises: 5df13f3f88cc
Create Date: 2024-04-05 21:54:32.401866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8ad1b4f8dc'
down_revision: Union[str, None] = '5df13f3f88cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('capacity', sa.Integer(), nullable=False))
    op.drop_constraint('student_group_team_id_fkey', 'student_group', type_='foreignkey')
    op.drop_constraint('student_group_uid_fkey', 'student_group', type_='foreignkey')
    op.create_foreign_key(None, 'student_group', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_group', 'website_user', ['uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_group', type_='foreignkey')
    op.drop_constraint(None, 'student_group', type_='foreignkey')
    op.create_foreign_key('student_group_uid_fkey', 'student_group', 'website_user', ['uid'], ['uid'])
    op.create_foreign_key('student_group_team_id_fkey', 'student_group', 'team', ['team_id'], ['id'])
    op.drop_column('project', 'capacity')
    # ### end Alembic commands ###
