"""Add optional email to subject

Revision ID: e0c97995e669
Revises: d0e0719b1939
Create Date: 2024-05-01 14:23:11.789984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c97995e669'
down_revision: Union[str, None] = 'd0e0719b1939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'publish_date',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('subject', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'email')
    op.alter_column('project', 'publish_date',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
