"""primary_key

Revision ID: ec4231ba1311
Revises: b7c0c893a6f7
Create Date: 2024-04-04 20:52:58.529167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4231ba1311'
down_revision: Union[str, None] = 'b7c0c893a6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructor_subject', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('instructor_subject', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_subject', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student_subject', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_primary_key("pk_instructor_subject","instructor_subject",["uid","subject_id"])
    op.create_primary_key("pk_student_subject","student_subject",["uid","subject_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_subject', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_subject', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('instructor_subject', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instructor_subject', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint("pk_instructor_subject","instructor_subject")
    op.drop_constraint("pk_student_subject","student_subject")
    # ### end Alembic commands ###
