"""update project scheme

Revision ID: ecbdc859aca6
Revises: 29a17fa183de
Create Date: 2024-03-12 16:43:51.794097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbdc859aca6'
down_revision: Union[str, None] = '29a17fa183de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('project', 'deadline',
                    existing_type=sa.DATE(),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    op.alter_column('project', 'subject_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.alter_column('project', 'enroll_deadline',
                    existing_type=sa.DATE(),
                    type_=sa.DateTime(),
                    existing_nullable=True)
    op.drop_constraint('project_subject_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'subject', [
                          'subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')  # type: ignore
    op.create_foreign_key('project_subject_id_fkey', 'project', 'subject', [
                          'subject_id'], ['id'], ondelete='SET NULL')
    op.alter_column('project', 'enroll_deadline',
                    existing_type=sa.DateTime(),
                    type_=sa.DATE(),
                    existing_nullable=True)
    op.alter_column('project', 'subject_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=True)
    op.alter_column('project', 'deadline',
                    existing_type=sa.DateTime(),
                    type_=sa.DATE(),
                    existing_nullable=False)
    op.alter_column('project', 'id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
