"""add checks files path

Revision ID: fdd2552f4fa1
Revises: a88aec136b59
Create Date: 2024-04-06 15:00:01.294724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd2552f4fa1'
down_revision: Union[str, None] = 'a88aec136b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project',
                  sa.Column('check_files_uuid', sa.String(), nullable=False, server_default="placeholder"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'check_files_uuid')
    # ### end Alembic commands ###
