"""Add default publish date to Project

Revision ID: fe818acfa209
Revises: a88aec136b59
Create Date: 2024-04-04 22:16:28.606016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe818acfa209'
down_revision: Union[str, None] = 'a88aec136b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('publish_date', sa.DateTime(
        timezone=True), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'publish_date')
    # ### end Alembic commands ###
