name: Code Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Node (frontend) dependencies
        working-directory: frontend
        run: npm ci
      - name: Install Python linting (backend) dependencies
        run: pip install autopep8

      - name: Run Frontend linters
        working-directory: frontend
        run: |
          npm run lint
          npm run format:check

      - name: Run Backend linter
        run: autopep8 -rd --exit-code backend
 
  pytest:
    name: Backend Unit Testing
    runs-on: self-hosted
    env:
      DATABASE_URI: "${{ secrets.POSTGRES_CONNECTION }}"
      FRONTEND_URL: "https://localhost:8080"
      CAS_SERVER_URL: "https://login.ugent.be"
      SECRET_KEY: "test" 
      ALGORITHM: "HS256" 
      FILE_PATH: "files"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Initialize Database
      working-directory: backend
      run: |
        alembic upgrade head
    - name: Test with pytest
      working-directory: backend
      run: |
        pip install pytest pytest-cov pytest-html pytest-sugar pytest-json-report
        py.test -v --cov --html=../reports/pytest/report.html
    - name: Archive pytest coverage results
      uses: actions/upload-artifact@v1
      with:
        name: pytest-coverage-report
        path: reports/pytest/
    - name: clean up alembic
      working-directory: backend
      if: always()
      run: alembic downgrade base

  vitest:
    name: Frontend Unit Testing
    runs-on: self-hosted
    env:
      VITE_APP_URL: https://localhost:8080
      VITE_API_URL: http://localhost:5173
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run Tests
      run: npm run test:unit

  pyright:
    name: Pyright
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyright

    - name: run pyright
      working-directory: backend
      run: |
        pyright
