name: Code Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Node (frontend) dependencies
        working-directory: frontend
        run: npm ci
      - name: Install Python linting (backend) dependencies
        run: pip install autopep8

      - name: Run Frontend linters
        working-directory: frontend
        run: |
          npm run lint
          npm run format:check

      - name: Run Backend linter
        run: autopep8 -rd --exit-code backend
 
  pytest:
    name: Unit Testing
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Initialize Database
      working-directory: backend
      run: |
        psql -U selab -p 2002 -d selab < selab_script.sql
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-html pytest-sugar pytest-json-report
        DATABASE_URI='postgresql://selab@127.0.0.1:2002/selab' py.test -v --cov --html=reports/pytest/report.html
    - name: Archive pytest coverage results
      uses: actions/upload-artifact@v1
      with:
        name: pytest-coverage-report
        path: reports/pytest/
  pyright:
    name: Pyright
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyright

    - name: run pyright
      working-directory: backend
      run: |
        pyright
